name: Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install sphinx sphinx-rtd-theme myst-parser sphinx-autodoc-typehints
    
    - name: Create docs directory structure
      run: |
        mkdir -p docs/_static docs/_templates
    
    - name: Create Sphinx configuration
      run: |
        cat > docs/conf.py << 'CONFEOF'
        import os
        import sys
        sys.path.insert(0, os.path.abspath('..'))
        
        project = 'Treadmill'
        copyright = '2024, Treadmill Contributors'
        author = 'Treadmill Contributors'
        
        extensions = [
            'sphinx.ext.autodoc',
            'sphinx.ext.viewcode',
            'sphinx.ext.napoleon',
            'sphinx_rtd_theme',
            'myst_parser',
        ]
        
        templates_path = ['_templates']
        exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
        
        html_theme = 'sphinx_rtd_theme'
        html_static_path = ['_static']
        
        napoleon_google_docstring = True
        napoleon_numpy_docstring = True
        napoleon_include_init_with_doc = False
        napoleon_include_private_with_doc = False
        CONFEOF
    
    - name: Create index documentation
      run: |
        cat > docs/index.rst << 'INDEXEOF'
        Treadmill Documentation
        =======================
        
        Welcome to Treadmill's documentation!
        
        .. toctree::
           :maxdepth: 2
           :caption: Contents:
        
           api
        
        Indices and tables
        ==================
        
        * :ref:`genindex`
        * :ref:`modindex`
        * :ref:`search`
        INDEXEOF
    
    - name: Create API documentation
      run: |
        cat > docs/api.rst << 'APIEOF'
        API Reference
        =============
        
        .. automodule:: treadmill
           :members:
           :undoc-members:
           :show-inheritance:
        
        .. automodule:: treadmill.trainer
           :members:
           :undoc-members:
           :show-inheritance:
        
        .. automodule:: treadmill.config
           :members:
           :undoc-members:
           :show-inheritance:
        
        .. automodule:: treadmill.metrics
           :members:
           :undoc-members:
           :show-inheritance:
        
        .. automodule:: treadmill.callbacks
           :members:
           :undoc-members:
           :show-inheritance:
        
        .. automodule:: treadmill.utils
           :members:
           :undoc-members:
           :show-inheritance:
        APIEOF
    
    - name: Build documentation
      run: |
        cd docs
        sphinx-build -b html . _build/html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html